# Generated by Django 5.0.6 on 2024-06-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("carbs", models.FloatField()),
                ("portein", models.FloatField()),
                ("fats", models.FloatField()),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
